import { describe, it, expect } from 'vitest'
import { nextTick } from 'vue'
import { mount } from '@vue/test-utils'
import { z } from 'zod'
import { expectA11y, mountBody, tick } from '../helpers'
import { UiInput, UiTextarea, UiSelect, UiCombobox, UiCheckbox, UiSwitch, UiDateInput, UiNumberInput, UiFilePicker, UiSecretField, UiTagEditor, UiForm, UiField } from '@/index'
import { useZodForm, nonEmpty } from '@/forms'

describe('fields', () => {
  it('wire label, hint, error (aria-describedby / aria-invalid) and emit v-model + blur', async () => {
    const w = mountBody(UiInput, { props: { id: 'name', label: 'Name', hint: 'Your name', required: true } })
    const input = w.find('input')
    expect(w.find('label').attributes('for')).toBe('name')
    expect(input.attributes('aria-describedby')).toBe('name-hint')
    expect(input.attributes('data-field')).toBe('name')
    await input.setValue('Ann')
    expect(w.emitted('update:modelValue')?.[0]).toEqual(['Ann'])
    await input.trigger('blur')
    expect(w.emitted('blur')).toHaveLength(1)
    await w.setProps({ error: 'Required' })
    expect(input.attributes('aria-invalid')).toBe('true')
    expect(input.attributes('aria-describedby')).toBe('name-error')
    expect(w.find('[role=alert]').text()).toBe('Required')
    expect(input.classes()).toContain('is-invalid')
    await input.trigger('keyup.enter')
    expect(w.emitted('enter')).toHaveLength(1)
    await expectA11y(w.element)
    w.unmount()
  })
  it('number input emits numbers, date input trims ISO to a day, textarea/select/checkbox/switch bind', async () => {
    const n = mount(UiNumberInput, { props: { id: 'n', label: 'N' } })
    await n.find('input').setValue('12.5')
    expect(n.emitted('update:modelValue')?.[0]).toEqual([12.5])
    await n.find('input').setValue('')
    expect(n.emitted('update:modelValue')?.[1]).toEqual([''])
    const d = mount(UiDateInput, { props: { id: 'd', label: 'D', modelValue: '2025-01-02T10:00:00Z' } })
    expect((d.find('input').element as HTMLInputElement).value).toBe('2025-01-02')
    const t = mount(UiTextarea, { props: { id: 't', label: 'T' } })
    await t.find('textarea').setValue('x')
    expect(t.emitted('update:modelValue')?.[0]).toEqual(['x'])
    const s = mount(UiSelect, { props: { id: 's', label: 'S', options: [{ title: 'A', value: 'a' }], modelValue: '' } })
    await s.find('select').setValue('a')
    expect(s.emitted('update:modelValue')?.[0]).toEqual(['a'])
    expect(s.emitted('change')?.[0]).toEqual(['a'])
    const c = mount(UiCheckbox, { props: { id: 'c', label: 'C', error: 'bad' } })
    await c.find('input').setValue(true)
    expect(c.emitted('update:modelValue')?.[0]).toEqual([true])
    expect(c.find('[role=alert]').text()).toBe('bad')
    const sw = mount(UiSwitch, { props: { id: 'sw', label: 'On', hint: 'h' } })
    await sw.find('input').setValue(true)
    expect(sw.emitted('update:modelValue')?.[0]).toEqual([true])
    expect(sw.find('input').attributes('role')).toBe('switch')
  })
  it('secret field: masked, autocomplete off, reveal toggle, nothing persisted', async () => {
    localStorage.clear()
    const w = mountBody(UiSecretField, { props: { id: 'pw', label: 'Password', modelValue: 'hunter2' } })
    const input = w.find('input')
    expect(input.attributes('type')).toBe('password')
    expect(input.attributes('autocomplete')).toBe('off')
    expect(input.attributes('data-lpignore')).toBe('true')
    await w.find('button[aria-pressed]').trigger('click')
    expect(w.find('input').attributes('type')).toBe('text')
    await w.find('input').setValue('new-secret')
    expect(w.emitted('update:modelValue')?.[0]).toEqual(['new-secret'])
    expect(localStorage.length).toBe(0)
    expect(sessionStorage.length).toBe(0)
    const r = mount(UiSecretField, { props: { id: 'x', label: 'X', revealable: false, autocomplete: 'one-time-code' } })
    expect(r.find('button').exists()).toBe(false)
    expect(r.find('input').attributes('autocomplete')).toBe('one-time-code')
    await expectA11y(w.element)
    w.unmount()
  })
  it('combobox filters, navigates with arrows, selects with Enter, clears', async () => {
    const w = mountBody(UiCombobox, { props: { id: 'cb', label: 'Pick', options: [{ title: 'Alpha', value: 'a' }, { title: 'Beta', value: 'b' }, { title: 'Gamma', value: 'g' }], modelValue: '' } })
    const input = w.find('input[role=combobox]')
    await input.trigger('focus')
    expect(w.findAll('[role=option]')).toHaveLength(3)
    await input.setValue('a')
    expect(w.findAll('[role=option]').map((o) => o.text())).toEqual(['Alpha', 'Beta', 'Gamma']) // all contain 'a'
    await input.setValue('gam')
    expect(w.findAll('[role=option]')).toHaveLength(1)
    await input.trigger('keydown', { key: 'ArrowDown' })
    await input.trigger('keydown', { key: 'ArrowUp' })
    await input.trigger('keydown', { key: 'Enter' })
    expect(w.emitted('update:modelValue')?.at(-1)).toEqual(['g'])
    await w.setProps({ modelValue: 'g' })
    await nextTick()
    expect((w.find('input').element as HTMLInputElement).value).toBe('Gamma')
    await w.find('button[aria-label=Clear]').trigger('mousedown')
    expect(w.emitted('update:modelValue')?.at(-1)).toEqual([''])
    await w.setProps({ modelValue: '' })
    await input.setValue('zzz')
    expect(w.text()).toContain('No matches')
    await input.trigger('keydown', { key: 'Escape' })
    await input.trigger('blur')
    await new Promise((r) => setTimeout(r, 150))
    expect(w.emitted('blur')).toHaveLength(1)
    // click an option
    await input.trigger('focus')
    await input.setValue('')
    await w.findAll('[role=option] button')[1]!.trigger('mousedown')
    expect(w.emitted('update:modelValue')?.at(-1)).toEqual(['b'])
    await expectA11y(w.element)
    w.unmount()
  })
  it('file picker enforces maxBytes and shows the file; tag editor adds/removes', async () => {
    const f = mount(UiFilePicker, { props: { id: 'f', label: 'File', maxBytes: 5 } })
    const big = new File(['123456'], 'big.txt')
    const small = new File(['12'], 'small.txt')
    const input = f.find('input[type=file]').element as HTMLInputElement
    Object.defineProperty(input, 'files', { value: [big], configurable: true })
    await f.find('input').trigger('change')
    expect(f.emitted('too-large')).toHaveLength(1)
    expect(f.emitted('update:modelValue')?.[0]).toEqual([null])
    Object.defineProperty(input, 'files', { value: [small], configurable: true })
    await f.find('input').trigger('change')
    expect(f.emitted('update:modelValue')?.[1]?.[0]).toBe(small)
    await f.setProps({ modelValue: small })
    expect(f.text()).toContain('small.txt')
    const t = mount(UiTagEditor, { props: { id: 't', label: 'Tags', modelValue: { env: 'prod' }, max: 2 } })
    await t.find('input').setValue('team=core')
    await t.find('input').trigger('keydown.enter')
    expect(t.emitted('update:modelValue')?.[0]).toEqual([{ env: 'prod', team: 'core' }])
    await t.setProps({ modelValue: { env: 'prod', team: 'core' } })
    await t.find('input').setValue('third=x')
    await t.find('input').trigger('keydown.enter')
    expect(t.emitted('update:modelValue')).toHaveLength(1) // max reached
    await t.find('button[aria-label="Remove tag env"]').trigger('click')
    expect(t.emitted('update:modelValue')?.[1]).toEqual([{ team: 'core' }])
    await t.find('input').setValue('   ')
    await t.find('input').trigger('blur')
    expect(t.emitted('blur')).toHaveLength(1)
  })
  it('UiForm submits through the zod form and shows the server banner', async () => {
    const S = z.object({ name: nonEmpty(5) })
    let payload: unknown
    let handle: ReturnType<typeof useZodForm<typeof S>> | undefined
    const w = mountBody({
      components: { UiForm, UiInput, UiField },
      setup() {
        const form = useZodForm(S, { onSubmit: (p) => { payload = p } })
        handle = form
        return { form }
      },
      template: `<UiForm :form="form"><UiInput v-bind="form.field('name')" label="Name" /><button type="submit">Go</button></UiForm>`,
    })
    await w.find('form').trigger('submit')
    await tick()
    expect(payload).toBeUndefined()
    expect(w.find('[role=alert]').text()).toBe('This field is required.')
    expect(document.activeElement?.getAttribute('data-field')).toBe('name')
    await w.find('input').setValue('Ann')
    await w.find('form').trigger('submit')
    await tick()
    expect(payload).toEqual({ name: 'Ann' })
    handle!.setServerError(new (await import('@/api/client')).ApiError(409, 'conflict'))
    await nextTick()
    expect(w.text()).toContain('not possible')
    await w.find('button[aria-label=Dismiss]').trigger('click')
    expect(handle!.serverError.value).toBe('')
    w.unmount()
  })
})
