import { describe, it, expect, vi } from 'vitest'
import { nextTick } from 'vue'
import { expectA11y, mountBody, setViewport, tick } from '../helpers'
import { UiDialog, UiDrawer, UiConfirm, UiDropdownMenu, UiTooltip, UiToast, UiTabs, UiAccordion, useConfirm, useToast } from '@/index'

describe('UiDialog', () => {
  it('traps focus, closes on Esc/backdrop/close button, restores focus, full-screen below md', async () => {
    setViewport(1280)
    const trigger = document.createElement('button')
    trigger.textContent = 'open'
    document.body.appendChild(trigger)
    trigger.focus()
    const w = mountBody(UiDialog, { props: { modelValue: true, title: 'Hello' }, slots: { default: '<input id="a" aria-label="A" /><button id="b">b</button>', actions: '<button id="c">c</button>' } })
    await tick()
    const dialog = document.body.querySelector('[role=dialog]')!
    expect(dialog.getAttribute('aria-modal')).toBe('true')
    expect(dialog.getAttribute('aria-labelledby')).toBeTruthy()
    expect(document.activeElement?.id).toBe('a')
    // Tab from the last control wraps to the first (the header close button); Shift+Tab wraps back.
    ;(document.getElementById('c') as HTMLElement).focus()
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Tab', bubbles: true }))
    expect(document.activeElement?.getAttribute('aria-label')).toBe('Close')
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Tab', shiftKey: true, bubbles: true }))
    expect(document.activeElement?.id).toBe('c')
    expect(document.body.classList.contains('overflow-hidden')).toBe(true)
    await expectA11y(dialog)
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
    expect(w.emitted('update:modelValue')?.[0]).toEqual([false])
    await w.setProps({ modelValue: false })
    await tick()
    expect(document.activeElement).toBe(trigger)
    expect(document.body.classList.contains('overflow-hidden')).toBe(false)
    w.unmount()
    // persistent ignores Esc + backdrop
    const p = mountBody(UiDialog, { props: { modelValue: true, title: 'P', persistent: true } })
    await tick()
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
    ;(document.body.querySelector('.fixed.inset-0') as HTMLElement).dispatchEvent(new MouseEvent('mousedown', { bubbles: true }))
    expect(p.emitted('update:modelValue')).toBeUndefined()
    p.unmount()
    setViewport(360)
    const m = mountBody(UiDialog, { props: { modelValue: true, title: 'Phone' } })
    await tick()
    expect(document.body.querySelector('[role=dialog]')?.className).toContain('h-full')
    ;(document.body.querySelector('button[aria-label=Close]') as HTMLElement).click()
    expect(m.emitted('update:modelValue')?.[0]).toEqual([false])
    m.unmount()
    setViewport(1280)
  })
})

describe('UiDrawer + UiConfirm', () => {
  it('drawer is a dialog with close; confirm host resolves the promise', async () => {
    const d = mountBody(UiDrawer, { props: { modelValue: true, title: 'Detail' }, slots: { default: '<p>x</p>', actions: '<button>ok</button>' } })
    await tick()
    expect(document.body.querySelector('aside[role=dialog]')).toBeTruthy()
    ;(document.body.querySelector('button[aria-label=Close]') as HTMLElement).click()
    expect(d.emitted('update:modelValue')?.[0]).toEqual([false])
    d.unmount()
    const host = mountBody(UiConfirm)
    const { ask } = useConfirm()
    const p = ask({ title: 'Delete?', text: 'sure', danger: true, confirmLabel: 'Delete' })
    await nextTick()
    await tick()
    expect(document.body.textContent).toContain('Delete?')
    const btn = Array.from(document.body.querySelectorAll('button')).find((b) => b.textContent?.trim() === 'Delete')!
    expect(btn.className).toContain('btn-error')
    btn.click()
    expect(await p).toBe(true)
    const p2 = ask({ title: 'Again' })
    await nextTick()
    await tick()
    Array.from(document.body.querySelectorAll('button')).find((b) => b.textContent?.trim() === 'Cancel')!.click()
    expect(await p2).toBe(false)
    const p3 = ask({ title: 'Third' })
    const p4 = ask({ title: 'Fourth' }) // supersedes: third resolves false
    expect(await p3).toBe(false)
    useConfirm().answer(true)
    expect(await p4).toBe(true)
    host.unmount()
  })
})

describe('UiDropdownMenu', () => {
  it('opens, arrows move focus, Enter selects, Esc closes, outside click closes', async () => {
    const w = mountBody(UiDropdownMenu, { props: { items: [{ key: 'a', label: 'A' }, { key: 'b', label: 'B', disabled: true }, { key: 'c', label: 'C', danger: true }] } })
    const btn = w.find('button[aria-haspopup=menu]')
    await btn.trigger('keydown', { key: 'ArrowDown' })
    await tick()
    expect(w.find('[role=menu]').exists()).toBe(true)
    expect(document.activeElement?.textContent?.trim()).toBe('A')
    await w.trigger('keydown', { key: 'ArrowDown' })
    expect(document.activeElement?.textContent?.trim()).toBe('C') // disabled skipped
    await w.trigger('keydown', { key: 'ArrowDown' })
    expect(document.activeElement?.textContent?.trim()).toBe('A')
    await w.trigger('keydown', { key: 'End' })
    expect(document.activeElement?.textContent?.trim()).toBe('C')
    await w.trigger('keydown', { key: 'Home' })
    ;(document.activeElement as HTMLElement).click()
    await nextTick()
    expect(w.emitted('select')?.[0]).toEqual(['a'])
    expect(w.find('[role=menu]').exists()).toBe(false)
    await btn.trigger('click')
    expect(w.find('[role=menu]').exists()).toBe(true)
    await w.find('[role=menuitem][aria-disabled=true]').trigger('click')
    expect(w.emitted('select')).toHaveLength(1)
    await w.trigger('keydown', { key: 'Escape' })
    await tick()
    expect(w.find('[role=menu]').exists()).toBe(false)
    await btn.trigger('click')
    document.body.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }))
    await nextTick()
    expect(w.find('[role=menu]').exists()).toBe(false)
    await expectA11y(w.element)
    w.unmount()
  })
})

describe('UiToast / UiTooltip / UiTabs / UiAccordion', () => {
  it('toast host shows, times out and dismisses', async () => {
    vi.useFakeTimers()
    const host = mountBody(UiToast)
    const toast = useToast()
    toast.clear()
    const id = toast.success('Saved', 'ok')
    toast.error('Failed')
    toast.show({ kind: 'warning', title: 'Sticky', timeout: 0 })
    await nextTick()
    expect(host.findAll('.alert')).toHaveLength(3)
    toast.dismiss(id)
    await nextTick()
    expect(host.findAll('.alert')).toHaveLength(2)
    vi.advanceTimersByTime(9000)
    await nextTick()
    expect(host.findAll('.alert')).toHaveLength(1)
    await host.find('button[aria-label=Dismiss]').trigger('click')
    expect(host.findAll('.alert')).toHaveLength(0)
    toast.info('i')
    toast.warning('w')
    toast.clear()
    vi.useRealTimers()
    host.unmount()
  })
  it('tooltip is focusable with the text as label', () => {
    const w = mountBody(UiTooltip, { props: { text: 'Help' }, slots: { default: '<span>?</span>' } })
    expect(w.attributes('data-tip')).toBe('Help')
    expect(w.attributes('tabindex')).toBe('0')
    w.unmount()
  })
  it('tabs use roving focus and arrow keys', async () => {
    const w = mountBody(UiTabs, { props: { modelValue: 'a', tabs: [{ key: 'a', label: 'A', icon: 'mdi-laptop' }, { key: 'b', label: 'B', count: 3 }] } })
    expect(w.find('[role=tab][aria-selected=true]').text()).toContain('A')
    await w.find('[role=tablist]').trigger('keydown', { key: 'ArrowRight' })
    expect(w.emitted('update:modelValue')?.[0]).toEqual(['b'])
    await w.find('[role=tablist]').trigger('keydown', { key: 'End' })
    await w.find('[role=tablist]').trigger('keydown', { key: 'Home' })
    await w.find('[role=tablist]').trigger('keydown', { key: 'ArrowLeft' })
    await w.find('[role=tablist]').trigger('keydown', { key: 'x' })
    await w.findAll('[role=tab]')[1]!.trigger('click')
    expect(w.emitted('update:modelValue')?.length).toBeGreaterThan(2)
    await expectA11y(w.element)
    w.unmount()
  })
  it('accordion renders native details', async () => {
    const w = mountBody(UiAccordion, { props: { items: [{ key: 'x', title: 'X', subtitle: 's' }, { key: 'y', title: 'Y' }], open: ['x'] }, slots: { x: '<p>inner</p>' } })
    expect(w.findAll('details')).toHaveLength(2)
    expect(w.find('details').attributes('open')).toBeDefined()
    await expectA11y(w.element)
    w.unmount()
  })
})
