// @freya/ui — components + composables. Forms live in @freya/ui/forms, the API
// client in @freya/ui/api, the theme in @freya/ui/theme.css.
export { default as UiIcon } from './components/UiIcon.vue'
export { default as UiPage } from './components/UiPage.vue'
export { default as UiToolbar } from './components/UiToolbar.vue'
export { default as UiGrid } from './components/UiGrid.vue'
export { default as UiCard } from './components/UiCard.vue'
export { default as UiSection } from './components/UiSection.vue'
export { default as UiAlert } from './components/UiAlert.vue'
export { default as UiBadge } from './components/UiBadge.vue'
export { default as UiStatusChip } from './components/UiStatusChip.vue'
export { default as UiEmptyState } from './components/UiEmptyState.vue'
export { default as UiErrorState } from './components/UiErrorState.vue'
export { default as UiSkeleton } from './components/UiSkeleton.vue'
export { default as UiAvatar } from './components/UiAvatar.vue'
export { default as UiCopyButton } from './components/UiCopyButton.vue'
export { default as UiLiveIndicator } from './components/UiLiveIndicator.vue'
export { default as UiButton } from './components/UiButton.vue'
export { default as UiDialog } from './components/UiDialog.vue'
export { default as UiDrawer } from './components/UiDrawer.vue'
export { default as UiConfirm } from './components/UiConfirm.vue'
export { default as UiDropdownMenu } from './components/UiDropdownMenu.vue'
export type { MenuItem } from './components/UiDropdownMenu.vue'
export { default as UiTooltip } from './components/UiTooltip.vue'
export { default as UiToast } from './components/UiToast.vue'
export { default as UiTabs } from './components/UiTabs.vue'
export type { TabItem } from './components/UiTabs.vue'
export { default as UiAccordion } from './components/UiAccordion.vue'
export type { AccordionItem } from './components/UiAccordion.vue'
export { default as UiField } from './components/UiField.vue'
export { default as UiInput } from './components/UiInput.vue'
export { default as UiNumberInput } from './components/UiNumberInput.vue'
export { default as UiDateInput } from './components/UiDateInput.vue'
export { default as UiSecretField } from './components/UiSecretField.vue'
export { default as UiTextarea } from './components/UiTextarea.vue'
export { default as UiSelect } from './components/UiSelect.vue'
export type { SelectOption } from './components/UiSelect.vue'
export { default as UiCombobox } from './components/UiCombobox.vue'
export { default as UiCheckbox } from './components/UiCheckbox.vue'
export { default as UiSwitch } from './components/UiSwitch.vue'
export { default as UiFilePicker } from './components/UiFilePicker.vue'
export { default as UiTagEditor } from './components/UiTagEditor.vue'
export { default as UiForm } from './components/UiForm.vue'
export { default as UiFieldRenderer } from './components/UiFieldRenderer.vue'
export { default as UiRecordForm } from './components/UiRecordForm.vue'
export { default as UiRecordDialog } from './components/UiRecordDialog.vue'
export { default as UiRecordDrawer } from './components/UiRecordDrawer.vue'
export { default as UiDataTable } from './components/UiDataTable.vue'
export type { Column } from './components/UiDataTable.vue'
export { default as UiKeyValueTable } from './components/UiKeyValueTable.vue'
export type { KeyValue } from './components/UiKeyValueTable.vue'
export { default as UiStatTile } from './components/UiStatTile.vue'
export { default as UiStatGrid } from './components/UiStatGrid.vue'
export { default as UiBarList } from './components/UiBarList.vue'
export type { BarItem } from './components/UiBarList.vue'
export { default as UiPagination } from './components/UiPagination.vue'
export { default as UiTree } from './components/UiTree.vue'
export type { TreeNode } from './components/UiTree.vue'
export { default as UiDocumentList } from './components/UiDocumentList.vue'
export type { DocumentRow } from './components/UiDocumentList.vue'
export { default as UiAuditTable } from './components/UiAuditTable.vue'
export type { AuditRow } from './components/UiAuditTable.vue'
export { default as UiPermissionDrawer } from './components/UiPermissionDrawer.vue'
export type { Grant } from './components/UiPermissionDrawer.vue'
export { default as UiAppShell } from './components/UiAppShell.vue'
export { default as UiNavDrawer } from './components/UiNavDrawer.vue'
export type { NavItem, NavGroup } from './components/UiNavDrawer.vue'
export { default as UiAppBar } from './components/UiAppBar.vue'
export { default as UiUserMenu } from './components/UiUserMenu.vue'
export { default as UiRemoteBoundary } from './components/UiRemoteBoundary.vue'

export { useBreakpoint, prefersReducedMotion, BREAKPOINTS } from './composables/useBreakpoint'
export type { Breakpoint } from './composables/useBreakpoint'
export { useTheme, THEME_KEY } from './composables/useTheme'
export type { Theme } from './composables/useTheme'
export { useToast } from './composables/useToast'
export type { Toast, ToastKind, ToastOptions } from './composables/useToast'
export { useConfirm } from './composables/useConfirm'
export type { ConfirmOptions } from './composables/useConfirm'
export { useFocusTrap } from './composables/useFocusTrap'
export { usePermissionGrants } from './composables/usePermissionGrants'
export type { PermissionGrantsDeps, StoreGrant, GrantRequest } from './composables/usePermissionGrants'
export { iconClass, ICONS, ICON_CLASS_SAFELIST } from './icons'
export type { IconName } from './icons'
